name: 'NPM Auth Token'
description: 'Generates an NPM auth token for publishing a specific package'

inputs:
  package-name:
    description: 'The name of the package to publish'
    required: true
  github-token:
    description: 'the github token'
    required: true
  wombat-token-cli:
    description: 'The npm token for the cli package.'
    required: true

outputs:
  auth-token:
    description: 'The generated NPM auth token'
    value: '${{ steps.npm_auth_token.outputs.auth-token }}'

runs:
  using: 'composite'
  steps:
    - name: 'Generate NPM Auth Token'
      id: 'npm_auth_token'
      shell: 'bash'
      run: |
        AUTH_TOKEN="${{ inputs.github-token }}"
        PACKAGE_NAME="${{ inputs.package-name }}"
        if [[ "$PACKAGE_NAME" == "@perplexity-cli/perplexity-cli" ]]; then
          AUTH_TOKEN="${{ inputs.wombat-token-cli }}"
        fi
        echo "auth-token=$AUTH_TOKEN" >> $GITHUB_OUTPUT